name: Deploy Service 1 to ECS

on:
  push:
    branches:
      - main  # Trigger the workflow on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Log in to Amazon ECR Public
      run: |
        aws ecr-public get-login-password --region ${{ secrets.AWS_REGION }} | \
        docker login --username AWS --password-stdin public.ecr.aws

    - name: Build Docker image for Service 1
      run: |
        docker build -t ms-public .

    - name: Tag Docker image for Public ECR
      run: |
        docker tag ms-public:latest public.ecr.aws/ms-public/ms-public:latest

    - name: Push Service 1 image to Public ECR
      run: |
         docker push public.ecr.aws/ms-public/ms-public:latest
